configMap:
  mountPath: /opt/gohello/params

app:
  http:
    port: 8080

  istio:
    injected: true

  readiness:
    path: /health_check

  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 200m
      memory: 1Gi

migration:
  enabled: true

  configMap: "gohello-app-prod"

  command:
    - gohello

  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 200m
      memory: 1Gi

ingress:
  enabled: false

virtualService:
  enabled: true

  gateways:
    - backend-gateway/backend-gateway

  hosts:
    - gohello.local

  routes:
    - match:
        - uri:
            prefix: /gohello/
      retries:
        attempts: 3
        perTryTimeout: 2s
      rewrite:
        uri: /
      route:
        - destination:
            host: gohello-app-prod
            port:
              number: 80
          weight: 100
      corsPolicy:
        allowOrigin:
          - "*"
        allowMethods:
          - POST
          - GET
        allowHeaders:
          - "*"
        maxAge: "24h"

autoscaling:
  minReplicas: 2
  maxReplicas: 20

users:
